---
title: "HW3"
author: "Eric, Kaiyi, Sidharth, Kai"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r results='hide', message=FALSE, warning=FALSE,echo=FALSE}
library(stat297)
```


#Problem #1

```{r}
find.pi = function (B = 5000,seed=10,make_plot=TRUE){
  if (make_plot == TRUE){
    #Plot Template Generated
    par(pty="s")
    plot(NA, xlim = c(-1.1,1.1), ylim = c(-1.1,1.1), xlab = "x", ylab = "y")
    grid()
    cols = hcl(h = seq(15, 375, length = 3), l = 65, c = 100, alpha = 0.2)[1:2]
    make_square(col="blue")
    points(0.8, 0.9, pch = 16, col = cols[1])
    points(0, 0, pch = 16, col = cols[2])
    make_circle(col="red")
    #Monte Carlo Simulation
    set.seed(seed)
    point = matrix(runif(2*B,-1,1),B,2)
    count = 0
    for (i in 1:B){
      if (point[i,1]^2+point[i,2]^2<=1) {
        #Plots if inside
        count = count + 1
        points(point[i,1],point[i,2],col=rgb(0,1,1, alpha=0.2),pch=19)
      }else{
        #Plots if outside
        points(point[i,1],point[i,2],col=rgb(1,0,0, alpha=0.1),pch=19)}
        }
    hat.pi = 4*(count/B)
    return(hat.pi)  
  }else{
    #Monte Carlo Simulation
    set.seed(seed)
    count = 0
    point = matrix(runif(2*B,-1,1),B,2)
    for (i in 1:B){if (point[i,1]^2+point[i,2]^2<=1){count = count + 1}}
    hat.pi = 4*(count/B)
    return(hat.pi)
    }
}
find.pi(make_plot=TRUE)
find.pi(B=10^8,make_plot=FALSE)
```

#Problem #2


```{r}
get_position = function(distance){
  if (is.matrix(distance)==FALSE && length(distance)%%3 == 0){
    distance=matrix(c(distance),ncol=3,nrow=(length(distance))/3,byrow=T)
  }else if (length(distance)%%3!=0){
    return(warning("Input is a vector and of invalid length"))
  }
  n = nrow(distance)
  out=matrix(0,n,3)
  for(i in 1:n){
    d = distance[i,]
    Theta = c(0,0,0)
    xy = matrix(c(-300,300,0,300,300,-300),3,2)
    lst_sq = function(Theta, xy=xy, d=d){
      calc = ((xy[1,1]-Theta[1])^2+(xy[1,2]-Theta[2])^2-(d[1]-Theta[3])^2)^2+
        ((xy[2,1]-Theta[1])^2+(xy[2,2]-Theta[2])^2-(d[2]-Theta[3])^2)^2+
        ((xy[3,1]-Theta[1])^2+(xy[3,2]-Theta[2])^2-(d[3]-Theta[3])^2)^2
      return(calc)
    }
    out[i,] = optim(Theta, fn = lst_sq, d = d, xy=xy)$par
  }
  class(out) = "mylm"
  return(out)
}

summary.mylm = function(obj){
  n = nrow(obj)
  print("The estimated position is:")
  for(i in 1:n){
    cat(paste("X = ", round(obj[i,1],4),",","Y = ", 
              round(obj[i,2],4),"\n", sep = " "))
    
  }
}

plot.mylm=function(obj){
  cols = hcl(h = seq(15, 375, length = 4), l = 65, c = 100)[1:3]
  cols_trans = hcl(h = seq(15, 375, length = 4), l = 65, c = 100, alpha = 0.15)[1:3]
  par(pty="s")
  plot(NA, xlim = c(-310, 310), ylim = c(-310, 310), xlab = "x", ylab = "y")
  grid()
  make_circle(fill = "lightgrey", radius = 200, lty = 1)
  make_circle(radius = 20, center = c(-300, 300), col = cols[1], fill = cols[1])
  make_circle(radius = 20, center = c(300, 300), col =cols[2], fill = cols[2])
  make_circle(radius = 20, center = c(0, -300), col = cols[3], fill = cols[3])
  points(obj[,1], obj[,2],pch =4, col = "orange")
}

position = get_position(c(453.2136, 288.8427, 418.3106))
summary(position)
plot(position)

dist_mat=matrix(c(458.9474, 337.1013, 363.1112,
                  337.0894, 458.9355, 363.0993,
                  442.5835, 442.5835, 283.9493,
                  520.1845, 520.1845, 184.0449,
                  534.1411, 499.0299, 191.3455,
                  499.1322, 534.2434, 191.4479,
                  542.0904, 470.4216, 212.7515,
                  470.4070, 542.0758, 212.7369,
                  541.6032, 429.4569, 250.9978,
                  429.4120, 541.5583, 250.9528),nrow = 10, byrow = T)

add_point = get_position(dist_mat)
summary(add_point)
plot(add_point)
```
